
spring:
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:postgresql://localhost:5432/shiro
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  #这里使用freemarker开发静态页面
  freemarker:
    suffix: .html
    charset: utf-8
server:
  port: 19873
